apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: name
          operator: In
          values: [in-cluster]
  template:
    metadata:
      name: '{{cluster}}-my-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/arunvthangaraj/app-gitops.git
        path: argo-app
        targetRevision: main
      destination:
        server: '{{server}}'
        namespace: default
