apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-bluegreen-appset
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          spoke: "true"
  template:
    metadata:
      name: '{{name}}-my-bluegreen-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/arunvthangaraj/app-gitops.git
        path: app-manifest/blue-green
        targetRevision: main
      destination:
        server: '{{server}}'
        namespace: default
